### ISSUE TITLE
Add sparklines for finer grained graphs

### ISSUE THREAD

**Issue by webwurst** [linkedin/asciietch#3]
Just as an idea, make use of `▁▂▃▅▇` like [holman/spark](https://github.com/holman/spark) does, to create more pleasant graphs.

**Comment by durgaswaroop** [comment]
I would like to try this one out. And for implementing the bar graphs, we don't have to restrict ourselves to just one line. We can do multi lines.

**Comment by scallister** [comment]
I think this would make a great addition. @durgaswaroop go for it! :)

**Comment by scallister** [comment]
Completed by @durgaswaroop, in https://github.com/linkedin/asciietch/pull/9

**Comment by scallister** [comment]
Available now on PyPI in version `1.0.6`.
